class CountException(Exception):
    pass


class BoundsException(Exception):
    pass